---
- hosts: app
  vars:
    docker_registry: nexus3.inspq.qc.ca:5000
  
  roles:
  - docker-engine
      
  tasks:

  - name: Docker repository logon
    shell: docker login -u {{ docker_registry_username }} -p  {{ docker_registry_password }} -e {{ docker_registry_email }} {{ docker_registry }}
    when: docker_registry_username is defined and docker_registry_password is defined and docker_registry_email is defined
    
  - name: Mettre a jour l'image Docker
    docker_image: 
      name: "nexus3.inspq.qc.ca:5000/inspq/testgatling"
      tag: "latest"
      pull: true
      state: present
      force: yes
      
  - name: Creation du conteneur
    docker_container:
      name: "containertestgatling"
      image: "nexus3.inspq.qc.ca:5000/inspq/testgatling"
      state: started
      volumes: "/tmp/gatling/results:/opt/gatling/results"
      command: "-s computerdatabase.TestSimulation"
      detach: false
    register: dockerexec

  - name: Message du conteneur
    debug:
      msg: "{{ dockerexec.Output }}"